"""Initial clear migration

Revision ID: d563c8e34192
Revises: 
Create Date: 2026-05-07 11:07:41.637756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd563c8e34192'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS postgis')
    op.execute('SET search_path TO public, tiger, topology'),
    op.create_table('developers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('feed_url', sa.String(), nullable=True),
    sa.Column('feed_format', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_developers_id'), 'developers', ['id'], unique=False)
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('developer_id', sa.Integer(), nullable=False),
    sa.Column('building', sa.String(), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=False),
    sa.Column('apartment_number', sa.String(), nullable=False),
    sa.Column('area', sa.Float(), nullable=False),
    sa.Column('rooms', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', spatial_index=False), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['developer_id'], ['developers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('building', 'floor', 'apartment_number', 'area', name='uq_property_attributes')
    )
    op.create_index('idx_properties_location', 'properties', ['location'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_properties_id'), 'properties', ['id'], unique=False)
    op.create_table('price_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price_histories')
    op.drop_index(op.f('ix_properties_id'), table_name='properties')
    op.drop_index('idx_properties_location', table_name='properties', postgresql_using='gist')
    op.drop_table('properties')
    op.drop_index(op.f('ix_developers_id'), table_name='developers')
    op.drop_table('developers')
    # ### end Alembic commands ###
